service:
    name: auction-service

plugins:
    - serverless-webpack
    - serverless-reqvalidator-plugin
    - serverless-aws-documentation
    - serverless-iam-roles-per-function

custom:
    documentation:
        api:
            info:
                version: v1.0.0
                title: Auction API
                description: Serverless Auction Application
        models:
            - name: CreateAuctionRequest
              contentType: application/json
              schema: ${file(src/utils/validators/create-auction-request.json)}
            - name: UpdateBidRequest
              contentType: application/json
              schema: ${file(src/utils/validators/update-bid-request.json)}

provider:
    name: aws
    runtime: nodejs12.x
    memorySize: 256
    stage: ${opt:stage, 'dev'}
    region: ${opt:region, 'us-east-1'}
    environment: # global environment variables - accessible to all lambda functions
        AUCTION_TABLE: AuctionTable-${self:provider.stage}

functions:
    createAuction:
        handler: src/lambda/http/createAuction.handler
        events:
            - http:
                  method: POST # post will also work
                  path: /auction
                  reqValidatorName: RequestBodyValidator
                  documentation:
                      summary: Create an Auction Item
                      description: Create an Auction Item
                      requestModels:
                          "application/json": CreateAuctionRequest
        iamRoleStatements:
            - ${file(iam/AuctionTableIAM.yml):AuctionTablePutItem}

    getAuctions:
        handler: src/lambda/http/getAuctions.handler
        events:
            - http:
                  method: get
                  path: /auctions
        iamRoleStatements:
            - ${file(iam/AuctionTableIAM.yml):AuctionTableScan}

    getAuction:
        handler: src/lambda/http/getAuction.handler
        events:
            - http:
                  method: get # GET will also work
                  path: /auction/{auctionId}
        iamRoleStatements:
            - ${file(iam/AuctionTableIAM.yml):AuctionTableGetItem}
    placeBid:
        handler: src/lambda/http/placeBid.handler
        events:
            - http:
                  method: patch # PATCH (all Caps) will also work
                  path: /auction/{auctionId}/bid
                  reqValidatorName: RequestBodyValidator
                  documentation:
                      summary: Update a Bid in Auction Item
                      description: Update a Bid in Auction Item
                      requestModels:
                          "application/json": UpdateBidRequest
        iamRoleStatements:
            - ${file(iam/AuctionTableIAM.yml):AuctionTableGetItem}
            - ${file(iam/AuctionTableIAM.yml):AuctionTableUpdateItem}

resources:
    # Now, since we are using AWS, the following syntax is particular to cloud formation syntax, NOT The Serverless Syntax
    Resources:
        AuctionTable: ${file(resources/AuctionTable.yml):AuctionTable}
        # Request Validator Resource
        RequestBodyValidator: ${file(resources/RequestBodyValidator.yml):RequestBodyValidator}
