service:
    name: auction-service

plugins:
    - serverless-bundle
    - serverless-pseudo-parameters

provider:
    name: aws
    runtime: nodejs12.x
    memorySize: 256
    stage: ${opt:stage, 'dev'}
    region: ${opt:region, 'us-east-1'}
    environment: # global environment variables - accessible to all lambda functions
        AUCTION_TABLE: AuctionsTable-${self:provider.stage}

functions:
    createAuction:
        handler: src/handlers/createAuction.handler
        events:
            - http:
                  method: POST
                  path: /auction

resources:
    # Now, since we are using AWS, the following syntax is particular to cloud formation syntax, NOT The Serverless Syntax
    Resources:
        AuctionsTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:provider.environment.AUCTION_TABLE}
                BillingMode: PAY_PER_REQUEST
                AttributeDefinitions: # Attributes that MUST BE in our table
                    - AttributeName: auctionId
                      AttributeType: S
                KeySchema: # Without Kwyschema, DynamoDB deployment won't work
                    - AttributeName: auctionId
                      KeyType: HASH # Hash means Partition key
