service:
    name: auction-service

plugins:
    - serverless-bundle
    - serverless-pseudo-parameters # This will allow us to use AWS values(like region, account ID) with some variables

provider:
    name: aws
    runtime: nodejs12.x
    memorySize: 256
    stage: ${opt:stage, 'dev'}
    region: ${opt:region, 'us-east-1'}
    environment: # global environment variables - accessible to all lambda functions
        AUCTION_TABLE: AuctionTable-${self:provider.stage}
    iamRoleStatements: # TODO: Currently IAM Roles defined for All lambdas, Need to change it for individual functions
        - Effect: Allow
          Action:
              - dynamodb:PutItem
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:UpdateItem
          Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.AUCTION_TABLE}

functions:
    createAuction:
        handler: src/handlers/createAuction.handler
        events:
            - http:
                  method: POST # post will also work
                  path: /auction
    getAuctions:
        handler: src/handlers/getAuctions.handler
        events:
            - http:
                  method: get
                  path: /auctions
    getAuction:
        handler: src/handlers/getAuction.handler
        events:
            - http:
                  method: get # GET will also work
                  path: /auction/{auctionId}
    placeBid:
        handler: src/handlers/placeBid.handler
        events:
            - http:
                  method: patch # PATCH (all Caps) will also work
                  path: /auction/{auctionId}/bid

# TODO: Move the Resources,Iam Roles to separate Files to make this serverless.yml file more readable
resources:
    # Now, since we are using AWS, the following syntax is particular to cloud formation syntax, NOT The Serverless Syntax
    Resources:
        AuctionTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:provider.environment.AUCTION_TABLE}
                BillingMode: PAY_PER_REQUEST
                AttributeDefinitions: # Attributes that MUST BE in our table
                    - AttributeName: auctionId
                      AttributeType: S
                KeySchema: # Without Kwyschema, DynamoDB deployment won't work
                    - AttributeName: auctionId
                      KeyType: HASH # Hash means Partition key
