RequestBodyValidator:
    Type: AWS::ApiGateway::RequestValidator
    Properties:
        Name: "request-body-validator"
        RestApiId:
            Ref: ApiGatewayRestApi # Reference of the API Gateway build by serverless framework
        ValidateRequestBody: true
        ValidateRequestParameters: false
